INSERT INTO ie_selfcares (user_id, content, type, rating, date_modified)
VALUES
        (2,'15 Mins of breathing exercise','physical', 5, now() - '22 days'::INTERVAL),
        (1,'Had a healthy breakfast bowl','energy', 4, now() - '21 days'::INTERVAL),
        (1,'Spoke to Deepa','emotional',5, now() - '19 days'::INTERVAL),
        (1,'Read a book about Sadhguru','spiritual',5, now() - '18 days'::INTERVAL),
        (1,'Moved furniture around the house','physical',3, now() - '21 days'::INTERVAL),
        (2,'Filled out my daily gratitude','spiritual',2, now() - '19 days'::INTERVAL),
        (2,'Went for a walk','physical',2, now() - '17 days'::INTERVAL),
        (2,'Had a small social gathering with two amazing ladies','emotional',5, now() - '19 days'::INTERVAL),
        (1,'Worked on a plan for my spiritual trip','spiritual',5, now() - '21 days'::INTERVAL),
        (2,'Ate some dark chocolate','emotional',5, now() - '19 days'::INTERVAL),
        (2,'Exploring a new town','emotional',5,now() - '21 days'::INTERVAL),
        (2,'Yoga practice','physical',4,now() - '20 days'::INTERVAL),
        (2,'15 minutes of breathing exercise','spiritual',5, now() - '19 days'::INTERVAL),
        (2,'Listened to the Paddison Podcast','emotional',5,now() - '18 days'::INTERVAL),
        (2,'Teaching Neel to write','physical',5,now() - '17 days'::INTERVAL),
        (2,'Worked on a new project','emotional',3, now() - '16 days'::INTERVAL),
        (2,'Meditated for 10 minutes','spiritual',4, now() - '15 days'::INTERVAL),
        (2,'Meditated for 20 minutes','spiritual',4, now() - '14 days'::INTERVAL),
        (2,'Meditated for 5 minutes','spiritual',3, now() - '13 days'::INTERVAL),
        (2,'Meditated for 15 minutes','spiritual',5, now() - '12 days'::INTERVAL),
        (2,'Meditated for 10 minutes','spiritual',4, now() - '11 days'::INTERVAL),
        (2,'Meditated for 10 minutes','spiritual',4, now() - '10 days'::INTERVAL),
        (2,'Meditated for 10 minutes','spiritual',4, now() - '9 days'::INTERVAL),
        (2,'Meditated for 20 minutes','spiritual',5,now() - '8 days'::INTERVAL),
        (2,'Meditated for 5 minutes','spiritual',3,now() - '7 days'::INTERVAL),
        (2,'Went for a run','physical',4,now() - '6 days'::INTERVAL),
        (2,'Worked on a new project','emotional',3,now() - '5 days'::INTERVAL),
        (2,'Cooked a new recipe','emotional',3,now() - '4 days'::INTERVAL);