INSERT INTO ie_gratitudes (user_id, content, date_modified)
VALUES
 (1,'I kept my cool with the building contractor',now() - '9 days'::INTERVAL),
 (1,'A catch up phone call with mom and Deepa', now() - '10 days'::INTERVAL),
 (2,'Watching Neel grow so fast',now() - '10 days'::INTERVAL),
 (2,'The yummy food I made for dinner last night',now() - '12 days'::INTERVAL),
 (2,'My family is getting healthy',now() - '12 days'::INTERVAL),
 (2,'New hikes',now() - '12 days'::INTERVAL),
 (2,'Neel''s amazingness',now() - '6 days'::INTERVAL),
 (2,'Sequin face masks',now() - '6 days'::INTERVAL),
 (2,'Good friends who check in on me always',now() - '6 days'::INTERVAL),
 (2,'Parents that are always there for you',now() - '14 days'::INTERVAL),
 (2,'Beautiful snowy days',now() - '14 days'::INTERVAL),
 (2,'Feeling inspired',now() - '14 days'::INTERVAL),
 (2,'Dark chocolate for dessert',now() - '13 days'::INTERVAL),
 (2,'More plants for the earth',now() - '13 days'::INTERVAL),
 (2,'Sitting in the sun reading a book',now() - '8 days'::INTERVAL),
 (2,'Bike rides with friends in the neighborhood',now() - '8 days'::INTERVAL),
 (2,'Loving my home',now() - '7 days'::INTERVAL),
 (2,'Sleeping in on a Sunday',now() - '7 days'::INTERVAL),
 (2,'Small social gatherings with friends',now() - '13 days'::INTERVAL),
 (2,'Bike rides with friends in the neighborhood',now() - '8 days'::INTERVAL),
 (2,'Loving the sunset view from my home',now() - '7 days'::INTERVAL),
 (2,'Meeting a good mentor and friend',now() - '7 days'::INTERVAL),
 (2,'Amazing coding journey at Thinkful',now() - '13 days'::INTERVAL)
 ;
